#!/bin/bash
set -e
source /system_shared/library.sh

if [[ "$ARCHITECTURE" = x86 ]]; then
	CHROOT_NAME=epel-7-i386
else
	CHROOT_NAME=epel-7-x86_64
fi
MOCK_NAME="$CHROOT_NAME-$RUBY_VERSION-$ARCHITECTURE"
run chown root:mock /var/lib/mock
run chmod g+ws /var/lib/mock
echo

header "Setting up chroot"
if $INITIALIZE; then
    # 这一步，其实是在 /var/cache/mock/ 下面新建一个 $CHROOT_NAME(epel-7-x86_64) 文件夹。
	run /system/setuser app /usr/bin/mock \
		-r $CHROOT_NAME \
		--uniqueext "$RUBY_VERSION-$ARCHITECTURE" \
		--init
fi
run /system/setuser app /usr/bin/mock  -r $CHROOT_NAME  --uniqueext "$RUBY_VERSION-$ARCHITECTURE"  --install yum
echo

header "Installing additional software inside chroot"
run rm -rf /var/lib/mock/$MOCK_NAME/root/system
run mkdir /var/lib/mock/$MOCK_NAME/root/system
run cp -R /system/* /var/lib/mock/$MOCK_NAME/root/system/
run cp -R /system_shared/* /var/lib/mock/$MOCK_NAME/root/system/
echo $ARCHITECTURE > /var/lib/mock/$MOCK_NAME/root/system/ARCHITECTURE
run /system/setuser app /usr/bin/mock  -r $CHROOT_NAME  --uniqueext "$RUBY_VERSION-$ARCHITECTURE"  --shell /system/setup-runtime-inside-mock
run rm -rf /var/lib/mock/$MOCK_NAME/root/system
echo "----- chroot left -----"
echo

header "Finished!"
